[workspace]
members = [
    "crates/cli",
    "crates/parser",
    "crates/reader",
    "crates/wasm",
]
resolver = "3"

[workspace.package]
description = "Tools for processing MOJ-XML cadastral data"
repository = "https://github.com/KotobaMedia/mojxml-rs"
authors = ["Keitaroh Kobayashi <keita@kotobamedia.com>"]
version = "0.2.1"
edition = "2024"
license = "MIT"

[workspace.metadata.release]
allow-branch = ["main"]

[profile.release]
# debug = true
codegen-units = 1
lto = false
panic = "abort"

[workspace.dependencies]
geo = "0.31"
geo-types = "0.7"
geoparquet-batch-writer = "0.1.4"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
