[package]
name = "mojxml-rs"
description = "A CLI tool to convert MOJ-XML files to GeoParquet, FlatGeobuf, or GeoJSON"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.release]
tag = true

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
flatgeobuf = { version = "5.0", default-features = false }
geo-types = { workspace = true }
geojson = "0.24.2"
geoparquet-batch-writer = { workspace = true }
geozero = "0.14"
indicatif = "0.18"
log = "0.4"
mojxml-parser = { version = "0.2.2", path = "../parser", features = ["geoparquet"] }
mojxml-reader = { version = "0.2.2", path = "../reader" }
num_cpus = "1"
serde = { workspace = true }
serde_json = "1"
simplelog = "0.12"
tempfile = { workspace = true }

[dev-dependencies]
geo = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0" }
