name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu

          - os: windows-latest
            arch: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.job.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # Fix to 1.89.0 until https://github.com/rust-lang/rust/issues/131960 is solved
          toolchain: 1.89.0
          target: ${{ matrix.job.arch }}
          components: clippy, rustfmt

      - name: Rust fmt check
        run: cargo fmt --check

      - name: Clippy check
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Release build check
        run: cargo build --release --target ${{ matrix.job.arch }}

      - name: Run test
        run: cargo test --workspace
